version: '3'

services:
  gpt4free:
    container_name: gpt-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '1337:1337'
    environment:
      - PYTHONUNBUFFERED=1